name: Bug
description: File a bug/issue
title: "[BUG] <title>"
labels: [Bug, Triage]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
  validations:
    required: false
- type: input
  id: version
  attributes:
    label: Version
    description: What version of the package are you using
  validations:
    required: true
- type: input
  id: SDK
  attributes:
    label: SDK
    description: What SDK are you seeing the problem on?
  validations:
      required: true
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false