name: Feature
description: Suggest an idea for this project
title: "[Feature] <title>"
labels: [Feature, Triage]
body:
- type: textarea
  attributes:
    label: Describe your problem
    description: Is your feature request related to a problem? Please describe.
    placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
  validations:
    required: false
- type: textarea
  attributes:
    label: Describe your ideal solution
    description: Describe the solution you'd like
    placeholder: A clear and concise description of what you want to happen.
  validations:
    required: false
- type: textarea
  attributes:
      label: Workarounds or alternatives
      description: Describe alternatives you've considered
  validations:
    required: false
- type: input
  attributes:
    label: Version
    description: What version and name of our packages are you running
  validations:
      required: true
- type: textarea
  attributes:
    label: Additional context
    description: Add any other context or screenshots about the feature request here.